### ISSUE TITLE
Could not obtain lock type 1 

### ISSUE THREAD

**Issue by Philoow** [owncloud-archive/files_locking#17]
I was trying to double click on a .ics file to import it in my calendars.
I've got this error. Any idea ? Running Owncloud 8

{\"Message\":\"Could not obtain lock type 1 on \\"\\/data\\/sHeitz\\/files\\/sheitz.ics\\".\",\"Code\":0,\"Trace\":\"#0 \\/home\\/repos\\/git\\/fus\\/owncloud\\/apps\\/files_locking\\/lib\\/lockingwrapper.php(44): OCA\\Files_Locking\\Lock->addLock(1, NULL)\n#1 \\/home\\/repos\\/git\\/fus\\/owncloud\\/apps\\/files_locking\\/lib\\/lockingwrapper.php(80): OCA\\Files_Locking\\LockingWrapper->getLock('files\\/sheitz.ic...', 1)

**Comment by SergioBertolinSG** [comment]
I have the same problem, also with type 2.

It is affecting deletions and versions.

https://github.com/owncloud/core/issues/16061
https://github.com/owncloud/core/issues/16062

**Comment by MorrisJobke** [comment]
@DeepDiver1975 We need to fix this. It seems to break a lot of stuff. @SergioBertolinSG has a env where we can reproduce this issue.

**Comment by jnfrmarks** [comment]
@icewind1991 @karlitschek 

FYI

**Comment by DeepDiver1975** [comment]
fixed with https://github.com/owncloud/files_locking/pull/29

**Comment by rperezb** [comment]
@SergioBertolinSG checked
