### ISSUE TITLE
[files_locking] Can locks stay forever ?

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud-archive/files_locking#20]
https://github.com/owncloud/apps/issues/1937

![screen shot 2015-05-05 at 14 52 09](https://cloud.githubusercontent.com/assets/1005065/7472793/619d70d0-f336-11e4-9702-84ea4764151a.png)

**Comment by ghost** [comment]
@DeepDiver1975 I think this can be closed as with owncloud/apps#1937

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 I think this can be closed as with owncloud/apps#1937

no - I moved the issue over from the apps repo

**Comment by PVince81** [comment]
goodbye files_locking app, closing as obsolete
