### ISSUE TITLE
[files_locking] $locks lost between calls of fopen()

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud-archive/files_locking#21]
https://github.com/owncloud/apps/issues/1922

![screen shot 2015-05-05 at 14 53 53](https://cloud.githubusercontent.com/assets/1005065/7472827/91c4227c-f336-11e4-8238-12ff970c101b.png)

**Comment by ghost** [comment]
@DeepDiver1975 I think this can be closed as of owncloud/apps#1922

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 I think this can be closed as of owncloud/apps#1922

no - i moved the issue over

**Comment by PVince81** [comment]
goodbye files_locking app, closing as obsolete
