### ISSUE TITLE
[files_locking] Potentially unclean fclose

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud-archive/files_locking#22]
https://github.com/owncloud/apps/issues/1921

![screen shot 2015-05-05 at 14 54 47](https://cloud.githubusercontent.com/assets/1005065/7472838/b3317446-f336-11e4-911e-c8343251617d.png)

**Comment by ghost** [comment]
This issue will fall off 8.2 if not resolved by 6 Oct

**Comment by DeepDiver1975** [comment]
dead coded -> close
