### ISSUE TITLE
Undefinex index

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud-archive/files_locking#26]
After migrating from v7 to v8 I see plenty of those warnings. Here an example from the log:

``` json


{
  "reqId": "b18a58d2fcbc2576a17515262b1aa208",
  "remoteAddr": "58.28.152.233",
  "app": "PHP",
  "message": "Undefined index: \/var\/www\/owncloud\/data\/michael.heuberger\/files_encryption\/keys\/M1\/home\/michael-heuberger\/Music\/Blood Sugar Sex Magik at \/var\/www\/owncloud\/apps\/files_locking\/lib\/lockingwrapper.php#140",
  "level": 3,
  "time": "2015-05-06T04:08:40+00:00"
}

```

**Comment by karlitschek** [comment]
argh. This was reported by a lot of different people. I thunk we have to look into that. @DeepDiver1975 Do you know if someone has time?

**Comment by karlitschek** [comment]
Ups. Just saw that you already work on that :-) Sweeet!!

**Comment by binarykitchen** [comment]
Hmmm, this bug happens a lot. Is there anything I could do right now to fix this on the server? Or should I wait until v8.0.4 is out?

**Comment by DeepDiver1975** [comment]
@binarykitchen you can try to apply 8739b42

**Comment by binarykitchen** [comment]
Problem is that I have installed it via apt-get.

Should I manually edit these files, according to your commit?
