### ISSUE TITLE
File locking locks wrong path

### ISSUE THREAD

**Issue by schiessle** [owncloud-archive/files_locking#34]
I just run into a problem with the file locking app. While debugging it I saw this line of code and wonder if this is correct:

https://github.com/owncloud/files_locking/blob/master/lib/lockingwrapper.php#L40

I assume that the intention is to get the complete path to the file. But for external storages this operation will create a local copy in the tmp folder and return the path to this file. Is this really what we want here?

cc @PVince81 @icewind1991 what do you think?

**Comment by DeepDiver1975** [comment]
Not a problem at all because the locking wrapper is only applied on local storages - https://github.com/owncloud/files_locking/blob/master/lib/lockingwrapper.php#L203

**Comment by schiessle** [comment]
But I observed that getLocalFile will return '/' if we call it for a file which doesn't yet exists, see https://github.com/owncloud/core/pull/16577 for more detail. This doesn't look correct to me.

**Comment by schiessle** [comment]
OK, my local copy of files_locking wasn't up-to-date. After a git pull the problem no longer happens and path is no longer resolved to '/'.
