### ISSUE TITLE
Show warning if combined with new locking

### ISSUE THREAD

**Issue by PVince81** [owncloud-archive/files_locking#36]
To avoid having two locking systems in place, we should show a warning in the admin page to inform the admin that both core filelocking and this app was enabled.

@jnfrmarks @DeepDiver1975 @icewind1991

**Comment by PVince81** [comment]
Not sure if really needed.
The old file_locking should be compatible with the new one.

I don't see this as critical/high.

**Comment by ghost** [comment]
@jnfrmarks this was I think at your request to eliminate admin confusion?

**Comment by jnfrmarks** [comment]
@cmonteroluque @PVince81 

Correct, I requested that we someone differentiate between the two, or at least have a conversation about it to see if it makes sense to do.

**Comment by PVince81** [comment]
Ok, now that the major locking issues were fixed on master there might still be a bit time left to implement this

**Comment by PVince81** [comment]
Moved to 8.1.1

**Comment by PVince81** [comment]
Obsolete, we got rid of this app anyway
