### ISSUE TITLE
Downloaded file is corrupted if another version of the file is uploaded at the same time

### ISSUE THREAD

**Issue by jvillafanez** [owncloud-archive/files_locking#38]
### Steps to reproduce
1. Upload a big file (several MB)
2. Download the file and, while the file is being downloaded, upload a new version
### Expected behaviour

The downloaded file is fine
### Actual behaviour

The downloaded file is corrupted. Download seems to be interrupted
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** OC 8.1 beta 2

**Updated from an older ownCloud or fresh install:** fresh install
### Notes

I've reproduced the bug consistently using smashbox (check https://github.com/owncloud/smashbox/pull/107 - first test). Target server is http://docker.oc.solidgear.es:50537

Also checked the same thing happens without the files_locking app enabled

**Comment by DeepDiver1975** [comment]
situations like that will be taken care of with the new/experimental high level locking

**Comment by ghost** [comment]
@jvillafanez @jnfrmarks ready for testing with files locking implementation?

**Comment by jnfrmarks** [comment]
@jvillafanez  Are you still seeing this issue?

**Comment by jvillafanez** [comment]
Not with with the daily package. I'm not sure if it's solved or I'm not putting enough pressure in the server (the downloaded file might be automatically fully cached into memory by the OS before being overwritten)
