### ISSUE TITLE
OS X Finder Write Access

### ISSUE THREAD

**Issue by jleidheiser** [owncloud-archive/files_locking#43]
Hello,
At the moment finder access ownCloud webdav readonly because Finder requries a webdav class 2  server expecially its file locking capabilities for write access. Can you give me a hint if this feature will be available in the near future?
I hope this is the right place for this question.

Best regards
Johannes Leidheiser

**Comment by tflidd** [comment]
There is as well an issue in core: https://github.com/owncloud/core/issues/17732
