### ISSUE TITLE
Undefined index: \/Users\/lreschke\/Programming\/core\/data\/admin\/files\/test at \/Users\/lreschke\/Programming\/core\/apps\/files_locking\/lib\/lockingwrapper.php#140

### ISSUE THREAD

**Issue by LukasReschke** [owncloud-archive/files_locking#8]
> {"reqId":"0ff2f50d6a7d6d497362964ff000f54e","remoteAddr":"::1","app":"PHP","message":"Undefined index: \/Users\/lreschke\/Programming\/core\/data\/admin\/files\/test at \/Users\/lreschke\/Programming\/core\/apps\/files_locking\/lib\/lockingwrapper.php#140","level":3,"time":"2015-02-16T23:06:50+00:00"}

On current master when deleting a folder.

@icewind1991

**Comment by enoch85** [comment]
I can confirm this.

```
Error   PHP Undefined index: /var/www/owncloud/data/user/files/Ny mapp at /var/www/owncloud/apps/files_locking/lib/lockingwrapper.php#140   2015-02-21T18:52:42+00:00
Error   PHP Undefined index: complete at /var/www/owncloud/apps/tasks/controller/helper.php#220 2015-02-21T18:49:11+00:00
```

**Comment by LukasReschke** [comment]
@DeepDiver1975 FYI - 8.1 or 8.0.1?

**Comment by karlitschek** [comment]
i think 8.0.1 would be good

**Comment by utack** [comment]
Just happened here as well. A fix would really be nice in 8.0.1
How does one resolve it when it happens?

**Comment by enoch85** [comment]
8.0.3?

**Comment by PeGa** [comment]
I can confirm this still happens in 8.0.2

**Comment by castanley** [comment]
Confirmed this is happening to me as well.

OC\Tags::__construct, tags: Array ( ) 

Undefined index: /home/REMOVED/domains/REMOVED/public_html/cloud/data/REMOVED/files_encryption/keys/hw8.txt at /home/REMOVED/domains/REMOVED/public_html/cloud/apps/files_locking/lib/lockingwrapper.php#140

**Comment by kaplandani** [comment]
same here on 8.0.2 got many of those....

**Comment by kroko** [comment]
+1 @8.0.2

**Comment by kaplandani** [comment]
Can anyone tell what happens when I get this error ? what implication does it have ?

**Comment by DeepDiver1975** [comment]
actually dup of https://github.com/owncloud/files_locking/issues/26

**Comment by DeepDiver1975** [comment]
fix is here - https://github.com/owncloud/files_locking/pull/27
